#!/usr/bin/env python3
"""Generate a static HTML docs site for the ASTHarbor rule set.

Reads `astharbor rules --format=json` output (either from stdin or by
invoking the binary) and writes one HTML page per rule plus an index.
No dependencies beyond the standard library.

Usage:

    tools/gen_rule_docs.py --binary ./build/astharbor --output docs/rules-site

The generated site is intentionally dependency-free: plain HTML + a tiny
inline stylesheet. Host it on GitHub Pages, S3, or any static host.
"""

from __future__ import annotations

import argparse
import html
import json
import pathlib
import subprocess
import sys
from collections import defaultdict


STYLE = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       max-width: 900px; margin: 2rem auto; padding: 0 1rem; color: #222;
       line-height: 1.5; }
h1 { border-bottom: 2px solid #333; padding-bottom: 0.3rem; }
h2 { margin-top: 2rem; color: #444; }
.rule-id { font-family: "SF Mono", Consolas, monospace; font-size: 1.1rem;
           background: #f4f4f4; padding: 0.2rem 0.4rem; border-radius: 3px; }
.badge { display: inline-block; padding: 0.15rem 0.5rem; border-radius: 3px;
         font-size: 0.85rem; font-weight: 600; margin-right: 0.4rem; }
.badge-error { background: #fde2e2; color: #8a1616; }
.badge-warning { background: #fff3cd; color: #6b5500; }
.badge-note { background: #e1ecf4; color: #1e4a6f; }
.category { color: #666; font-size: 0.95rem; }
ul.rule-list { list-style: none; padding-left: 0; }
ul.rule-list li { padding: 0.4rem 0; border-bottom: 1px solid #eee; }
ul.rule-list a { text-decoration: none; color: #1a4d8a; }
ul.rule-list a:hover { text-decoration: underline; }
.toc { background: #f9f9f9; padding: 1rem 1.5rem; border-radius: 5px; }
.footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee;
          color: #999; font-size: 0.85rem; }
"""


def severity_badge(severity: str) -> str:
    cls = {
        "error": "badge-error",
        "warning": "badge-warning",
        "note": "badge-note",
        "info": "badge-note",
    }.get(severity, "badge-warning")
    return f'<span class="badge {cls}">{html.escape(severity)}</span>'


def rule_filename(rule_id: str) -> str:
    return rule_id.replace("/", "__") + ".html"


def render_rule_page(rule: dict) -> str:
    rule_id = rule["id"]
    title = rule.get("title", rule_id)
    category = rule.get("category", "")
    severity = rule.get("severity", "warning")
    summary = rule.get("summary", "")
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>{html.escape(rule_id)} — ASTHarbor</title>
<style>{STYLE}</style>
</head>
<body>
<p><a href="index.html">&larr; All rules</a></p>
<h1><span class="rule-id">{html.escape(rule_id)}</span></h1>
<p>{severity_badge(severity)} <span class="category">category: {html.escape(category)}</span></p>
<h2>{html.escape(title)}</h2>
<p>{html.escape(summary)}</p>
<div class="footer">Generated by ASTHarbor rule docs generator.</div>
</body>
</html>
"""


def render_index(rules: list[dict]) -> str:
    by_category: dict[str, list[dict]] = defaultdict(list)
    for rule in rules:
        by_category[rule.get("category", "uncategorized")].append(rule)

    sections: list[str] = []
    for category in sorted(by_category.keys()):
        items: list[str] = []
        for rule in sorted(by_category[category], key=lambda r: r["id"]):
            badge = severity_badge(rule.get("severity", "warning"))
            items.append(
                f'<li><a href="{rule_filename(rule["id"])}">'
                f'<span class="rule-id">{html.escape(rule["id"])}</span></a> '
                f"{badge} {html.escape(rule.get('title', ''))}<br>"
                f'<small>{html.escape(rule.get("summary", ""))}</small></li>'
            )
        sections.append(
            f'<h2>{html.escape(category)}</h2>\n<ul class="rule-list">\n'
            + "\n".join(items)
            + "\n</ul>"
        )

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>ASTHarbor Rules</title>
<style>{STYLE}</style>
</head>
<body>
<h1>ASTHarbor Rules</h1>
<p>{len(rules)} rules across {len(by_category)} categories.</p>
<div class="toc">
<strong>Categories:</strong>
{" · ".join(f'<a href="#{html.escape(c)}">{html.escape(c)}</a>' for c in sorted(by_category.keys()))}
</div>
{"".join(f'<a id="{html.escape(c)}"></a>' + s for c, s in zip(sorted(by_category.keys()), sections))}
<div class="footer">Generated by ASTHarbor rule docs generator.</div>
</body>
</html>
"""


def load_rules(binary: pathlib.Path | None, json_path: pathlib.Path | None) -> list[dict]:
    if json_path is not None:
        return json.loads(json_path.read_text())
    if binary is not None:
        completed = subprocess.run(
            [str(binary), "rules", "--format=json"],
            capture_output=True,
            text=True,
            check=True,
        )
        return json.loads(completed.stdout)
    return json.loads(sys.stdin.read())


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--binary",
        type=pathlib.Path,
        help="Path to the astharbor binary (runs `rules --format=json`)",
    )
    parser.add_argument(
        "--json",
        type=pathlib.Path,
        help="Read rules JSON from this file instead of invoking the binary",
    )
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        required=True,
        help="Directory to write the generated site into",
    )
    args = parser.parse_args()

    rules = load_rules(args.binary, args.json)
    if not isinstance(rules, list):
        print(f"Error: expected JSON array of rules, got {type(rules).__name__}",
              file=sys.stderr)
        return 2

    args.output.mkdir(parents=True, exist_ok=True)
    (args.output / "index.html").write_text(render_index(rules))
    for rule in rules:
        (args.output / rule_filename(rule["id"])).write_text(render_rule_page(rule))

    print(f"Wrote {len(rules)} rule pages + index.html to {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
